...

diff --git a/devops/azure-pipelines/templates/fetch_app_service_name.yml b/devops/azure-pipelines/templates/fetch_app_service_name.yml
--- a/devops/azure-pipelines/templates/fetch_app_service_name.yml
+++ b/devops/azure-pipelines/templates/fetch_app_service_name.yml
@@ -1,13 +1,16 @@
 # devops/azure-pipelines/templates/fetch_app_service_name.yml
 # Template to fetch the App Service name from Terraform outputs
-
 parameters:
   subscription: ''
   terragrunt_path: ''
 
 steps:
   - bash: |
-      cd $(System.DefaultWorkingDirectory)/{{ parameters.terragrunt_path }}
+      echo "Changing to directory: $(System.DefaultWorkingDirectory)/{{ parameters.terragrunt_path }}"
+      cd "$(System.DefaultWorkingDirectory)/{{ parameters.terragrunt_path }}" || {
+        echo "Error: Directory not found: $(System.DefaultWorkingDirectory)/{{ parameters.terragrunt_path }}"
+        exit 1
+      }
       APP_SERVICE_NAME=$(terragrunt output -json | jq -r '.api_url.value')
       echo "##vso[task.setvariable variable=APP_SERVICE_NAME]$APP_SERVICE_NAME"
       if [ -z "$APP_SERVICE_NAME" ]; then
